### ISSUE TITLE
WP rdf files with incorrect DOI IRIs

### ISSUE THREAD

**Issue by marvinm2** [wikipathways/GPML2RDF#101]
With the March 2021 release, 3 WPs caused syntax errors in the Turtle files causing problems with data loading in the SPARQL endpoint:
- WP1919
- WP4432
- WP3395  (x2)

These have DOIs in them that do not work:
WP1919: <https://doi.org/10.1379/1466-1268(2003)8<37:IVRFVA>2.0.CO;2>
WP4432: <https://doi.org/10.1379/1466-1268(2001)006<0297:TNTATB>2.0.CO;2>
WP3395: <https://doi.org/10.1379/1466-1268(2004)009<0021:TRABOH>2.0.CO;2> and 
<https://doi.org/10.1379/1466-1268(1996)001<0237:APOMCI>2.3.CO;2>

These WPs are all Reactome converted and had a recent change

**Comment by egonw** [comment]
Fixed in https://github.com/wikipathways/GPML2RDF/commit/4d51d606635f9eb8a34ab9349e93bb6d6d552a74

**Comment by egonw** [comment]
Fixed in the development version.

**Comment by egonw** [comment]
Fixed now applied to master.
