### ISSUE TITLE
RDF has confusing datanodes for WP4657

### ISSUE THREAD

**Issue by marvinm2** [wikipathways/GPML2RDF#110]
Freddie asked me about this issue. WP4657 on WikiPathways has no histone genes but the RDF gives some: 
https://bit.ly/39a0jCu

Also the original ttl file does not have them. (attache
[WP4657.txt](https://github.com/wikipathways/GPML2RDF/files/7181086/WP4657.txt)
d)

Somehow these histone genes show up. What could be the cause?

**Comment by marvinm2** [comment]
All the histone genes seem to be linked to a list of ncbi genes and ensembl genes:
https://bit.ly/3AkinFM

But none of these appear in the WP

**Comment by marvinm2** [comment]
Found the cause in the WP (not gpml) rdf file for this pathway (attached)
[WP4657.txt](https://github.com/wikipathways/GPML2RDF/files/7181148/WP4657.txt)

 The protein annotated with <https://identifiers.org/uniprot/P62805> has all these names and IDs.

**Comment by fehrhart** [comment]
We know now where it comes from - but still may want to solve this mapping issue. Its not one pathway, but a few hundred which have this extensive histone gene mappings. And, these histones make according to the WP RDF the MOST ABUNDANT genes in WikiPathways:

![image](https://user-images.githubusercontent.com/11389574/133763638-2de27af8-7438-41f5-85eb-05bf532b4ef6.png)

Maybe with an updated bridgeDb for gene/geneproducts? or if it is from the source, check with Uniprot if that is really intended?

**Comment by egonw** [comment]
> Found the cause in the WP (not gpml) rdf file for this pathway (attached)
> [WP4657.txt](https://github.com/wikipathways/GPML2RDF/files/7181148/WP4657.txt)

This is something essential to realize: in the WikiPathways RDF world, WPRDF is *not* the "RDF of a pathway". That is the GPMLRDF. WPRDF is the *full* biological knowledge in WikiPathways.

**Comment by egonw** [comment]
"Debugged" it and the problem is the `P62805` UniProt identifiers in the pathways:

![image](https://user-images.githubusercontent.com/26721/133780890-f0699f74-618b-49f4-86de-f0e00e5a8418.png)

The multiple gene mappings come originally from Ensembl/UniProt:

![image](https://user-images.githubusercontent.com/26721/133780922-4d654180-5022-42d8-b1e3-10080320a044.png)

**Comment by egonw** [comment]
@fehrhart, there are 34 pathways with that UniProt identifier: https://bit.ly/39v8BFj

I have created a unit test for it.

**Comment by egonw** [comment]
Of these, 33 are Reactome pathways: https://bit.ly/3lD7GrK
