### ISSUE TITLE
Importing rdf to virtuoso reports syntax errors

### ISSUE THREAD

**Issue by nunogit** [wikipathways/GPML2RDF#14]
The importing process in virtuoso still reports syntactic errors on RDF import.
Several situations have been isolated

examples:

<http://identifiers.org/pubmed/1755382 > (space between 1755382 and >)
<http://identifiers.org/pubmed/ 10448523> (space between /  and 10448523)

Line number can be provided, but sine all the individual files were concatenated it won probably help.

**Comment by egonw** [comment]
Confirmed. I pushed a possible fix in https://github.com/wikipathways/GPML2RDF/commit/781808250f8ae973a1c63d263b3105052b499ce6

**Comment by egonw** [comment]
The problem occurs not in the WPRDF but in the GPMLRDF.

**Comment by egonw** [comment]
This may be fixed now. Jenkins created new RDF. It must still be verified with rapper...

**Comment by RyAMiller** [comment]
issue is fixed in most recent RDF generation

**Comment by nunogit** [comment]
Confirmed! :+1:  Thanks!
