### ISSUE TITLE
Two copies of Gpml.java

### ISSUE THREAD

**Issue by egonw** [wikipathways/GPML2RDF#3]

**Comment by egonw** [comment]
@mkutmon, which one is the right one?

**Comment by mkutmon** [comment]
I only see one Gpml.java - where is the copy?

**Comment by egonw** [comment]
These two:

    https://github.com/wikipathways/GPML2RDF/blob/master/WP2RDF/lib/Gpml.java
    https://github.com/wikipathways/GPML2RDF/blob/master/WP2RDF/src/main/java/org/wikipathways/wp2rdf/ontologies/Gpml.java

**Comment by mkutmon** [comment]
ah okay - the one in src is the one that is used. I guess the one in lib is the one generated from the OWL file and we just forgot to remove it.
