### ISSUE TITLE
VoID headers missing on http://data.wikipathways.org/20170210/rdf/

### ISSUE THREAD

**Issue by egonw** [wikipathways/GPML2RDF#36]
The VoID headers files must be files in that folder too (and for convenience handy to have in the zip file too).

Tina, the workflow (script, right) needs to be updated to also put the two VoID header files in the download folder.

**Comment by mkutmon** [comment]
@RyAMiller can you please prepare and upload the void headers for the release again? Thanks! Did you already progress with creating those automatically? Then I can update the release script to fetch them as well.

**Comment by mkutmon** [comment]
@egonw @RyAMiller I think there are still some manual steps in the void header creation. If not please let me know where to get them from.

**Comment by egonw** [comment]
Jenkins does indeed create headers now: https://jenkins.bigcat.unimaas.nl/job/GPML%20to%20GPML%20+%20WP%20RDF/ws/WP2RDF/output/

**Comment by mkutmon** [comment]
Yes but download location and URLs need to be adapted or not?

**Comment by egonw** [comment]
Yes. The script can do that, not?
