### ISSUE TITLE
RDF fails to generate, due to GPML parsing error

### ISSUE THREAD

**Issue by egonw** [wikipathways/GPML2RDF#40]
As reported by Jenkins... the cause seems to be a NPE in the GPML parsing code, see https://github.com/PathVisio/pathvisio/issues/49

**Comment by egonw** [comment]
For now, I'm going to add a try/catch to report an error message and skip that pathway.

**Comment by mkutmon** [comment]
probably would be easier/faster to remove the Reactome tag from the pathway but either works.

**Comment by egonw** [comment]
@mkutmon, OK, there are quite some pathways failing to read... search for "Error while reading the GPML" here: https://jenkins.bigcat.unimaas.nl/job/GPML%20to%20GPML%20+%20WP%20RDF%20(all)/998/consoleFull

**Comment by egonw** [comment]
The workaround: https://github.com/wikipathways/GPML2RDF/commit/ba83629a5ea994430b41568b50cc6fedc34bd042

**Comment by egonw** [comment]
No error messages anymore.
