### ISSUE TITLE
Unify HMDB IDs

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/GPML2RDF#50]
Hi all,

Since HMDB has a new identifier structure (from HMDBxxxx to HMDB00xxxx), there seems to be no unified ID structure in the RDF. (This was also the case for ChEBI a while ago, which showed CHEBI:yyyyy and yyyyy as two separate results). Example that I get out of the RDF for metabolites reactions (asking for source-target to create a network):

Source	Target	Occurences	CountPathways	IntTypes	Pathways
HMDB0001261	HMDB01097	1	1	[DirectedInteraction]	[WP3604]
HMDB01261	HMDB0001097	1	1	[DirectedInteraction]	[WP3604]

This will result in two separate reactions, which are not connected in a network (even though this is related to the same interaction).

**Comment by egonw** [comment]
@DeniseSl22, I think this is fixed now.

**Comment by DeniseSl22** [comment]
Checked, and yes this works on Jenkins :) Closing issue now!
