### ISSUE TITLE
Add Rhea IDs to RDF

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/GPML2RDF#56]
Example PW:
https://www.wikipathways.org/index.php/Pathway:WP4162

Since the Rhea info is not in the RDF, it would be nice to add this for DSMN.

**Comment by egonw** [comment]
Done.

```turtle
<http://rdf.wikipathways.org/Pathway/WP4162_r96442/WP/Interaction/ide55fb050>
        a                   wp:Conversion , wp:Interaction , wp:DirectedInteraction ;
        dc:source           "Rhea"^^xsd:string ;
        dcterms:identifier  "17213"^^xsd:string ;
        dcterms:isPartOf    <http://identifiers.org/wikipathways/WP4162_r96442> ;
        wp:bdbRhea          <http://identifiers.org/rhea/17213> .
```

**Comment by DeniseSl22** [comment]
Have to open this one again, due to a failure in PW : https://www.wikipathways.org/index.php/Pathway:WP4312
This doesn't include IDs on the interactions, but names of PWs (with spaces, which make the RDF unreadable). @egonw would like to build a test for this first, so before we fix the PW, check with him first!

**Comment by DeniseSl22** [comment]
I fixed all interaction IDs in the aforementioned PW, leaving one to build a Jenkins test on (with two spaces in the name).

**Comment by egonw** [comment]
Can you plz check it again?

**Comment by DeniseSl22** [comment]
?I will today ;)


Kind regards,

Denise Slenter MSc
UNS50 H1.302

T: +3143-3881962 (office)
T: +316-50585586 (mobile)

________________________________

**Comment by DeniseSl22** [comment]
Yes I can load in the RDF!
And with the following query:
```SPARQL
SELECT DISTINCT ?interaction ?PW ?rheaID WHERE {
 ?interaction a wp:Interaction.
  ?interaction dcterms:isPartOf ?PW .
  ?interaction wp:bdbRhea ?rheaID .  
  
} 
```
I even get results:
![image](https://user-images.githubusercontent.com/26277832/48905857-f9cd7f00-ee62-11e8-9191-0a374ca40304.png)
Probably the same 4 as you had @egonw

**Comment by DeniseSl22** [comment]
I checked the two PW which have Rhea IDs:
1. 
https://www.wikipathways.org/index.php/Pathway:WP3620
Also had other interaction annotations (such a BioCyc and KEGG-reaction).
I think we should standardise to Rhea finally (for now, there is not a lot of standardisation possible).

2.
https://www.wikipathways.org/index.php/Pathway:WP4162
Only gives a Rhea ID, when there is a source and a target compound. I believe this is intentional, but we have to check how to get the side metabolites then properly linked up to the reaction (and then later the RDF).

**Comment by egonw** [comment]
I checked and Rhea indeed has cross-links, under a CC-BY license. So we cannot use that in the RDF at this moment. But we can make sure we are compatible with their SPARQL endpoint: https://sparql.rhea-db.org/sparql

**Comment by DeniseSl22** [comment]
Okay, so how does that work then with the interaction mapping file we are creating from the Rhea webservice? Should we add a licence statement there? https://www.bridgedb.org/mapping-databases/rhea-interaction-mappings/

**Comment by egonw** [comment]
We'll have to talk to them.

**Comment by egonw** [comment]
Closing this issue for now. Getting more Rhea identifiers in WP is another issue.

**Comment by egonw** [comment]
Normalization to `wp:bdbRhea` can be checked in [WP4162](https://jenkins.bigcat.unimaas.nl/job/GPML%20to%20GPML%20+%20WP%20RDF%20(all-dev)/ws/WP2RDF/output/wp/Yeast/WP4162.ttl/*view*/).
