### ISSUE TITLE
Unit test for Wikidata as Protein/geneProduct ID

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/GPML2RDF#62]
Since we are not incorporating Wikidata into the mapping files for GeneProducts/Protein, people should not be allowed to add these for this DataNode type (I'll add an issue for that in PV/BridgeDb(datasources.txt). However, having a Unit test to detect these annotations, would be very helpful!

**Comment by egonw** [comment]
Unit test pushed.

**Comment by DeniseSl22** [comment]
Okay great thank you! I'll see which PWs need fixing, if it is a lot, then a curation cafe could be useful.

**Comment by egonw** [comment]
I had plenty of fails when running the test query on sparql.wikipathways.org but did not see fails on Jenkins yet... need to explore that later.
