### ISSUE TITLE
"Neutralized" InChIKey in the WPRDF

### ISSUE THREAD

**Issue by egonw** [wikipathways/GPML2RDF#68]
Denise suggested, and #MetSoc2019 showed how helpful it could be, to include the neutral InChIKey of metabolites. Before we do this, we need to make a few design decisions:

1. use CHEMINF? use wp:bdbXXXX?
2. how to represent this is not the InChI of the compound, but of the neutral variant

**Comment by egonw** [comment]
In progress, but not worked out yet... I don't see any InChIKeys in the output :(

**Comment by egonw** [comment]
I have a draft:

![image](https://user-images.githubusercontent.com/26721/68650806-2ff98800-0526-11ea-8548-1b75c490520d.png)

@DeniseSl22, what predicate should we use, in your opinion?

**Comment by DeniseSl22** [comment]
wp:neutralInchiKey ? Since it is not a direct mappin from bridgedb.... We should also add a good example on the SPARQL example page, so people can see the difference

**Comment by DeniseSl22** [comment]
See also https://github.com/wikipathways/GPML2RDF/pull/74 ; the wp:bdbInChIKey is present in the output now, however the neutral form is not (yet); I'm looking at the WP-RDF dev_all on Jenkins, last run on 2019-12-24 (job 2235) . So, I think the comment from @egonw on "Please integrate this into the outputBridgeDbMapping method." is still valid. Maybe we should implement that first to generate InChiKeys as mappings from BridgeDb, and then figure out how to provide neutralised ones?

**Comment by egonw** [comment]
it's push to master

**Comment by egonw** [comment]
Fixed and part of the March release:

```shell
grep -ri inchikey . | head -8
./Tomato/WP2631.ttl:        rdfs:seeAlso                   <http://identifiers.org/inchikey/LXJXRIRHZLFYRP-UHFFFAOYSA-N> ;
./Tomato/WP2631.ttl:        wp:bdbInChIKey                 <http://identifiers.org/inchikey/LXJXRIRHZLFYRP-UHFFFAOYSA-N> ;
./Tomato/WP2631.ttl:        rdfs:seeAlso                   <http://identifiers.org/inchikey/LXNHXLLTXMVWPM-UHFFFAOYSA-N> ;
./Tomato/WP2631.ttl:        wp:bdbInChIKey                 <http://identifiers.org/inchikey/LXNHXLLTXMVWPM-UHFFFAOYSA-N> ;
./Tomato/WP2631.ttl:        rdfs:seeAlso                   <http://identifiers.org/inchikey/NGHMDNPXVRFFGS-IUYQGCFVSA-N> ;
./Tomato/WP2631.ttl:        wp:bdbInChIKey                 <http://identifiers.org/inchikey/NGHMDNPXVRFFGS-IUYQGCFVSA-N> ;
./Tomato/WP2631.ttl:        rdfs:seeAlso        <http://identifiers.org/inchikey/MZJFVXDTNBHTKZ-UWTATZPHSA-N> ;
./Tomato/WP2631.ttl:        wp:bdbInChIKey      <http://identifiers.org/inchikey/MZJFVXDTNBHTKZ-UWTATZPHSA-N> ;
```
