### ISSUE TITLE
pathway ontology categories to be exposed?

### ISSUE THREAD

**Issue by egonw** [wikipathways/GPML2RDF#7]
@mkutmon @RyAMiller the WikiPathways wiki has a SPARQL query that currently not works and seems to use ontology tags:

    SELECT DISTINCT  *
    WHERE {
            ?pathway wp:category wp:MetabolicProcess .
            ?pathway dc:title ?title .
    } 

Should this example be removed, or should we add this triple to the WPRDF?

**Comment by mkutmon** [comment]
We don't have categories in WP anymore. Those have been removed. There might still be some stored in the GPML files themselves (we should clean those up) but the pathways are not categorized anymore.
