### ISSUE TITLE
check if the pathway description is in the RDF

### ISSUE THREAD

**Issue by egonw** [wikipathways/GPML2RDF#70]
and does it have a `Literal` data matching something like "HTML string"?

**Comment by AlexanderPico** [comment]
Question came up after looking at an example ttl for WP554 (attached as txt). It's got

- DataNodes
- Labels
- Shapes
- Interactions
- Publications

But that's it. No description.
[WP554.txt](https://github.com/wikipathways/GPML2RDF/files/3613251/WP554.txt)

**Comment by AlexanderPico** [comment]
The `wp` RDF of the same pathway (attached as txt) has this curious chunk:

```
<http://identifiers.org/wikipathways/WP554_r105430>
        a                      skos:Collection , wp:Pathway ;
        dc:identifier          <http://identifiers.org/wikipathways/WP554> ;
        dc:source              "WikiPathways"^^xsd:string ;
        dc:title               "ACE Inhibitor Pathway"@en ;
        dcterms:description    "" ;
        dcterms:identifier     "WP554"^^xsd:string ;
        dcterms:references     <http://identifiers.org/pubmed/17464936> ;
        wp:isAbout             <http://rdf.wikipathways.org/Pathway/WP554_r105430> ;
        wp:ontologyTag         <http://purl.obolibrary.org/obo/PW_0000245> , <http://vocabularies.wikipathways.org/wp#Curation:AnalysisCollection> , <http://purl.obolibrary.org/obo/PW_0001228> ;
        wp:organism            <http://purl.obolibrary.org/obo/NCBITaxon_9606> ;
        wp:organismName        "Homo sapiens"^^xsd:string ;
        wp:pathwayOntologyTag  <http://purl.obolibrary.org/obo/PW_0001228> , <http://purl.obolibrary.org/obo/PW_0000245> ;
        foaf:page              <http://www.wikipathways.org/instance/WP554_r105430> .
```

Note the `description` field. Maybe it's supposed to go there, but something in the pipeline broke?

[WP554-wp.txt](https://github.com/wikipathways/GPML2RDF/files/3613263/WP554-wp.txt)

**Comment by AlexanderPico** [comment]
And Andra just shared this query against the WikiPathways endpoint that returns descriptions for each pathway!?  So it must be in there somewhere...

https://paws-public.wmflabs.org/paws-public/User:Andrawaag/Wikipathways_email_scribles.ipynb

```
prefix dcterms:	<http://purl.org/dc/terms/>
SELECT ?item ?description WHERE {
   ?item wdt:P2410 ?wpid ;
         wdt:P2888 ?wpiri .
  SERVICE <http://sparql.wikipathways.org/> {
      ?version dc:identifier ?wpiri ;
               dcterms:description ?description .
    }
}
```

**Comment by AlexanderPico** [comment]
Ok. Mystery solved. The descriptions are there in the `wp` RDF. I just happened to check WP554 which is blank due to a recent change to the description that must be causing GPML2RDF to choke. I'll report that as a new bug.  But this can be closed: descriptions ARE in the RDF.
